### ISSUE TITLE
Mooncard export contains analytic account name and not code

### ISSUE THREAD

**Issue by wolh-dynapps** [akretion/odoo-mooncard-connector#4]
Hi,

Trying to import the Mooncard transactions into Odoo, the system doesn't take into account the Analytic account.
With further investigation, it seems that the Mooncard export contains the Analytic Name and not the Analytic Code as expected in your code.
Changing the Analytic Name by the Analytic Code makes the import working as expected.

2 questions : 
1. Did the mooncard export change?
2. Do you think adapting the module code is the good way of correcting this? 

Thanks

**Comment by wolh-dynapps** [comment]
After further investigation, the odoo export is not working correctly. 
Eg. Taxes are not correctly exported.

I'll try to reach the support

**Comment by alexis-via** [comment]
Seems the problem about analytic is/was a problem on the mooncard side, not in the odoo/mooncard connector. I don't use analytic for the accounting of my company, so my Mooncard export doesn't contain any analytic. If you raise the issue with the mooncard support team, I hope they will update the Odoo export.
I'll soon be working on adding the support for the Mooncard API... hope we won't need these stupid CSV files any more...
