### ISSUE TITLE
Missing attachment

### ISSUE THREAD

**Issue by joelgombin** [akretion/odoo-mooncard-connector#7]
When there is a missing attachment for an expense, and even if it has been marked as lost, there is this error when processing the line: "Missing image URL and/or attachments on transaction PAYCARD0023. If you lost that receipt, you can mark this transaction as 'Receipt Lost'." And indeed in the file exported from Mooncard I can't see any column indicating that the receipt has been marked as lost.

**Comment by alexis-via** [comment]
Which version ? 14.0 ?

**Comment by joelgombin** [comment]
yes

**Comment by alexis-via** [comment]
receipt_lost is not something that you import from mooncard CSV ; it is something that must be set manually by the user in Odoo, to acknownledge that he wants to create the invoice without any receipt.
When you look at the code https://github.com/akretion/odoo-mooncard-connector/blob/14.0/base_newgen_payment_card/models/newgen_payment_card_transaction.py#L358, I don't see how it's possible to get the error message when the option "Receipt Lost" is enabled. Do you have the latest code?

**Comment by joelgombin** [comment]
I don't know... @stephansainleger do you know?

**Comment by alexis-via** [comment]
Just put a print in the code at that place and check if self.receipt_lost is True. If yes, it should not execute the raise with the error msg.

**Comment by alexis-via** [comment]
Please re-open if you think there is really a bug.
